include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    missing_return: error
    missing_required_param: error
    constant_identifier_names: ignore
    use_build_context_synchronously: false
    sdk_version_async_exported_from_core: ignore
    no_leading_underscores_for_local_identifiers: ignore
  exclude:
    - "**.g.dart"
    - "**.config.dart"
    - "**.get_x_navigator.dart"
    - "**.mocks.dart"
    - "lib/util/license.dart"
    - "lib/cpp/native.cpp"
    - "test/coverage_helper_test.dart"
    - "tool/"

linter:
  rules:
    - unawaited_futures
    - always_declare_return_types
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - prefer_final_in_for_each
    - prefer_final_fields
    - prefer_final_locals
