# App Details
name: browser_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.3 <4.0.0"

# App Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Date utils package
  intl: ^0.18.1

  # Local storage
  shared_preferences: ^2.2.0

  # Custom util package
  flutter_approuter: ^3.0.4
  flutter_logger_plus: ^4.0.3

  # Restart app
  restart_app: ^1.2.1

  # Dependency Injection
  get_it: ^7.6.0

  # Dio
  dio: ^5.2.1+1
  dio_smart_retry: ^5.0.0

  # Class Generator
  freezed_annotation: any

  # Increase FPs
  flutter_displaymode: ^0.6.0

  # IOS icons
  cupertino_icons: ^1.0.2

  # Firebase Packages
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+4

  # Handle Permissions
  permission_handler: ^10.4.3

  # Get more info about user's screen
  flutter_screenutil: ^5.8.4

  # Check for internet connectivity
  connectivity_plus: ^4.0.1

  # Cache image locally
  cached_network_image: ^3.2.3

  # Custom error handler
  sentry_flutter: ^7.9.0

  # Custom icons
  font_awesome_flutter: ^10.5.0

  # Webview
  webview_flutter: ^4.2.2

  # Flutter downloader
  flutter_downloader: ^1.11.1

  # Path provider
  path_provider: ^2.1.0

  # Custom Toast
  fluttertoast: ^8.2.2

  # Android path provider(downloads dir)
  android_path_provider: ^0.3.0

  # State management
  flutter_riverpod: ^2.3.7

  # Local DB
  hive_flutter: ^1.1.0

  # Share url
  share_plus: ^7.1.0

  # Secondary webview
  flutter_inappwebview: ^5.7.2+3

  # screenshot provider
  screenshot: ^2.1.0

  # Speech to text
  speech_to_text: ^6.3.0

  # Flutter text_field
  flutter_typeahead: ^4.6.2

  # XML parser
  xml: ^6.3.0

  # Text to Speech
  flutter_tts: ^3.8.2

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Class Generator
  build_runner: any
  json_serializable: any
  freezed: any

  # Flutter icons Generator
  flutter_launcher_icons: ^0.13.1

  # Flutter Lints
  flutter_lints: ^2.0.0

  # Generate Splash Screen
  flutter_native_splash: ^2.3.2

# FLutter launcher icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

# Flutter config
flutter:
  uses-material-design: true
  assets:
    - assets/images/
