name: dart_s3_executor
description: A pubspec that is required for codemagic
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  yaml: ^3.1.1
  path: ^1.8.2
dev_dependencies:

