// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDrrkxRkbgbWvf717gTl3cP5XX804fs0',
    appId: '1:398435872877:android:dcf9900c677955af1fcf64',
    messagingSenderId: '398435872877',
    projectId: 'flutter-boilerplate-project-sk',
    storageBucket: 'flutter-boilerplate-project-sk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbA2-i3kk6fWy-aTPNEdvgSJ0wnei5js',
    appId: '1:398435872877:ios:ab393bca7d50e5881fcf64',
    messagingSenderId: '398435872877',
    projectId: 'flutter-boilerplate-project-sk',
    storageBucket: 'flutter-boilerplate-project-sk.appspot.com',
    androidClientId: '398435872877-oe8a78mplkaosihvsdulejo81jb676p1.apps.googleusercontent.com',
    iosClientId: '398435872877-abbq3gc1hqclkuav2l2fjefd7et0ggj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBoilerplateProject',
  );
}
